---
apiVersion: v1
kind: Service
metadata:
  name: basic-flask-api
spec:
  type: LoadBalancer
  selector:
    app: basic-flask-api
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-flask-api
  labels:
    app: basic-flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-flask-api
  template:
    metadata:
      labels:
        app: basic-flask-api
    spec:
      containers:
      - name: basic-flask-api
        image: oliveroscarlos/basic-flask-api:latest