name: Deploy Flask

on:
  [workflow_dispatch]
  # push:
  #   branches:
  #   - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.PROJECT_ID }}
      run: |
        gcloud container clusters get-credentials gke-cluster-1 --region us-central1
        sed -i "s/GOOGLE_PROJECT/$PROJECT_ID/g" resources.yaml
        kubectl apply -f resources.yaml