name: Testing Tags

on:
  # [workflow_dispatch]
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: code checkout
      uses: actions/checkout@v4

    - name: show tag
      run: echo "${{github.repository}}:${{github.ref_name}}"